# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [14]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001, size=(1000,20))

# print the shape of X
X

array([[3768, 1269, 2399, ..., 1990, 2355, 4536],
       [ 155, 1868, 4260, ..., 3343, 3233, 1947],
       [4235, 2532,  815, ..., 1908, 1148,  516],
       ..., 
       [2840, 3620, 3174, ..., 2803, 4638, 1027],
       [1855,  249, 2369, ..., 4091, 3574, 2470],
       [2532, 4666, 1081, ..., 4069, 1820, 2777]])

Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [15]:
# Average of the values in each column of X
avg_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)


If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [16]:
# Print the shape of avg_cols
print("avg_cols = ", avg_cols)

# Print the shape of std_cols
print("std_cols = ", std_cols)

avg_cols =  [ 2463.187  2488.628  2567.766  2566.138  2449.787  2480.375  2441.622
  2590.136  2534.93   2452.572  2439.86   2449.424  2477.595  2467.665
  2458.217  2517.635  2458.386  2525.268  2470.694  2432.985]
std_cols =  [ 1474.97500929  1449.4562317   1459.49297951  1438.31178573  1449.42472093
  1418.40223363  1469.91658305  1432.88998165  1452.64695887  1394.92421472
  1462.24494815  1443.65869104  1448.2996986   1445.41273025  1431.33065569
  1464.6545353   1445.25073569  1440.6569863   1459.66935858  1457.70119598]


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [17]:
# Mean normalize X
X_norm = (X - avg_cols) / std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [18]:
# Print the average of all the values of X_norm
print("The average of all the values of X_norm = ", X_norm.mean())

# Print the average of the minimum value in each column of X_norm
print("The average of the minimum value in each column of X_norm = ", X_norm.min(axis = 0))

# Print the average of the maximum value in each column of X_norm
print("The average of the maximum value in each column of X_norm = ", X_norm.max(axis = 0))

The average of all the values of X_norm =  4.26325641456e-18
The average of the minimum value in each column of X_norm =  [-1.66659569 -1.71417939 -1.75661414 -1.78343668 -1.68396948 -1.74800557
 -1.65902067 -1.80134974 -1.74297684 -1.75462722 -1.66651969 -1.69459999
 -1.70654941 -1.70585532 -1.71533879 -1.71824477 -1.70101003 -1.75285861
 -1.69058423 -1.66837004]
The average of the maximum value in each column of X_norm =  [ 1.71922438  1.73056071  1.65895556  1.68799423  1.75808579  1.77285747
  1.7364101   1.6727481   1.69213172  1.81689297  1.74877677  1.76189567
  1.740251    1.75198056  1.77022898  1.69348125  1.75236998  1.71778017
  1.7170368   1.75277005]


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [19]:
# We create a random permutation of integers 0 to 4
import numpy as np
np.random.permutation(5)#like arange but not in order

array([0, 3, 4, 2, 1])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [21]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices =np.random.permutation(1000)#numbers from 0 to 999 not in order
row_indices

array([781, 722, 955, 528, 208, 489, 696, 770, 398, 516, 234, 331, 279,
       525, 498,  61, 334, 571, 462, 653,  97, 338, 908, 126, 877, 649,
       796,   6, 150, 771, 669, 113, 788, 412, 259, 972, 577, 521, 911,
       224, 664, 302, 996, 975,  59, 585, 735, 278,  13,  76, 795, 684,
       934, 321, 260, 100,  55, 905, 166, 914, 834, 832, 775, 640, 612,
       348, 590, 962, 988, 613, 974, 712, 843, 157, 423, 526, 200, 408,
       557, 246, 617, 159, 852, 961, 921, 555, 822,   3, 333, 699, 448,
       130, 574, 439, 813, 441, 847, 930, 232, 112, 950, 790, 139, 197,
       756, 661, 938, 888, 297, 121, 430, 556, 592, 456, 135, 935, 369,
       530, 876, 825, 779, 457,  89, 226, 437, 761, 816,   2, 724, 561,
       158, 642, 951, 591, 774, 814, 303, 708, 881, 229, 210, 615, 466,
       225, 491, 288, 872, 309, 710, 389,  33, 869, 184, 110, 152, 454,
       968, 461, 773, 405, 548, 149, 940, 145, 114,  78, 727, 356,  54,
       913,  39, 244,  36, 858, 963, 726,  77,  19, 607, 187, 58

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [22]:
print("row_indices.shape is ", row_indices.shape)
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = X_norm[row_indices[0:600], :]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[600:800], :]

# Create a Test Set
X_test = X_norm[row_indices[800: ], :]

row_indices.shape is  (1000,)


If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [23]:
# Print the shape of X_train
print("The shape of X_train is : ", X_train.shape)

# Print the shape of X_crossVal
print("The shape of X_crossVal is : ", X_crossVal.shape)

# Print the shape of X_test
print("The shape of X_test is : ", X_test.shape)

The shape of X_train is :  (600, 20)
The shape of X_crossVal is :  (200, 20)
The shape of X_test is :  (200, 20)
